#!/bin/bash
echo -e "\nRunning in developer mode: using the engine source code at $MY_PATH\n"

if [ "$WORKSPACE." = "$MY_PATH." ]; then
  WORKSPACE=${MY_PATH}/testspace
  echo -e "Using ./testspace as /workspace\n"
fi

OTHER_VOLUMES="-v ${MY_PATH}:/root"
