#!/bin/bash

if [ "$1." = "-d." ]; then
  shift

  # Use the local code of the engine if available
  MY_PATH=$(dirname `readlink -f "$0"`)

  if [[ -f "${MY_PATH}/this-is-iati-workbench" ]]; then
    echo "Running in developer mode: using the engine source code at $MY_PATH"
    OTHER_VOLUMES="-v ${MY_PATH}:/home/iati-workbench"

    if [ "${PWD}" = "${MY_PATH}" ]; then
      echo "Error: cannot run in engine source code directory"
      exit 1
    fi
  fi
fi

if [ "$1." = "-t." ]; then
  shift
  
  DOCKER_TAG=":$1"
  shift

  echo -e "\nUsing Docker image tag version: ${DOCKER_TAG#:}\n"
fi

case "$1." in
  "-h.")
    cat <<EOT

$(basename $0)

  -d                     (Optional) Run in developer mode: mount the directory where iati-workbench resides
                         into the container as /home/iati-workbench. Must be the first argument.
  -t <version>           (Optional) Use the version tag to select the Docker image version. Defaults to 'latest'
  -h                     Show this help text.

  (without parameters)   Shows the available 'targets' the engine can create.
  -p                     Idem.
EOT
    ;;
  *)
    docker run --rm -u=`id -u`:`id -g` \
      -v "${PWD}":/workspace \
      -m 3g \
      $OTHER_VOLUMES \
      aida-s2i${DOCKER_TAG} $@
    ;;
esac
