#!/bin/bash

# Expect all targets, stylesheets and scripts to be in the same location as this script
ENGINE_PATH=$(dirname `readlink -f "$0"`)
# Use the directory where the engine is called from as the workspace
WORKSPACE=`pwd`
# Run the engine using our own user and group id's so we can manage the results
USER=`id -u`:`id -g`

# The parameter 'root' will run a bash shell as root with the rest as command
# The parameter 'bash' will run a bash shell as the current user with the rest as command
# With no parameters will jump into a bash shell as the current user
# With other parameters will run Ant as the current user
if [ "$1." = "root." ]; then
  USER="0:0"
  LINE=${@:2}
elif [ "$1." = "bash." ]; then
  LINE=${@:2}
elif [ "$1." = "show." ]; then
  LINE=${@:1}
elif [ "$1." != "." ]; then
  ENTRY="--entrypoint=ant"
  LINE=$@
else
  LINE=$@
fi

# local version of the engine for now...
docker run -it --rm -u=${USER} \
  -v ${ENGINE_PATH}:/root \
  -v ${WORKSPACE}:/workspace \
  -v iati-data:/iati-data \
  $ENTRY \
  iati-engine $LINE
