#!/bin/bash

# Expect all targets, stylesheets and scripts to be in the same location as this script
ENGINE_PATH=$(dirname `readlink -f "$0"`)
# Use the directory where the engine is called from as the workspace
WORKSPACE=`pwd`
# Run the engine using our own user and group id's so we can manage the results
USER=`id -u`:`id -g`

# local version of the engine for now...
docker run -it --rm -u=${USER} \
  -v ${ENGINE_PATH}:/root \
  -v ${WORKSPACE}:/workspace \
  -v iati-data:/iati-data \
  iati-engine $@
