= Spreadsheets2IATI engine

_Scripts to transform a set of input files (spreadsheets, IATI) into a combined IATI file._

== Build the container

[CAUTION]
====
Work in progress: a local workspace (directory on host machine) is still required to run.
This will become optional.

The local workspace directory has to be mounted under /workspace.
====

=== Option 1: localised build

In this case, the container will run as the user building the image.
You need to make sure it has proper permissions for the local workspace directory.

  $ docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t aida-s2i .

You should be able to run it and get a list of available targets:

  $ docker run --rm aida-s2i

Next, you can put the `iati-workbench` script in your path, for instance as a symlink:

`ln -s iati-workbench ~/bin/iati-workbench`

Then, verify everything is running:

`iati-workbench`

This will show the list of available "targets" in the workbench.

== Workspaces

You run the engine in a folder that will function as the 'workspace'.
You specify the task you want performed, and the engine will take all steps needed to transform the source data into the desired output formats.

The `iati-workbench` script will mount the current directory as the workspace.

Once you run any of the tasks, it will create the necessary folders for the source of your data, the intermediary files, and the output files generated.

You can run `iati-workbench init` to create those folders yourself.

=== Sample data

The https://github.com/data4development/demo-workspace[demo-workspace repository] contains example data files.

Clone the repository, and inside the directory, run

  $ iati-workbench spreadsheet-iati
  
This should process the input files and produce a raw IATI file in `src/`.

=== Acknowledgements

First inspiration came from https://github.com/KitWallace/AIDVIEW-DB[Kit Wallace's Aidview DB (working with eXist)]
