= Spreadsheets2IATI engine

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:icons: font
endif::[]

Scripts to transform a set of input files (spreadsheets, IATI) into a combined IATI file.

See https://developer.data4development.nl/iati-workbench/[the developer documentation website] for further details.

This includes setting up a demo workspace with example templates.

=== Acknowledgements

First inspiration came from https://github.com/KitWallace/AIDVIEW-DB[Kit Wallace's Aidview DB (working with eXist)]

TODO: in the root directory, aida-s2i is a symlink to iati-workbench, do they still both have value? If the only use is for you locally, maybe it could be a local thing for you, rather than for the remote repository.
TODO: Continuing on testing, would it be helpful for the testing setup to include some kind of CI/CD steps? Like having the tests run whenever you push and perhaps integrating some test coverage interface? @stefanos perhaps you could elaborate?
TODO: Not a requirement, but perhaps a description of the folders and what they are for could be useful. If that is already available in the antora docs, could be useful to make that known as well.
