= Introduction

The IATI Workbench provides a platform with tools to work with IATI data.

This version contains a Spreadsheets2IATI convertor.

* This section describes the general setup and structure.

* The xref:development:index.adoc[] section contains developer-specific tools and backgrounds.

* The xref:spreadsheets2iati:index.adoc[] section deals with the setup of the convertor
to turn spreadsheets and existing IATI files into new IATI data files.

== Running the workbench

The workbench uses two approaches to working with IATI data:

Container service::
It runs within a container:
all the necessary software runs within an isolated environment.

Build tool::
It runs as a software build tool:
it transforms input _source files_ into output _compiled files_.

=== Running as "container service"

The main code is intended to be used as Docker container.

This container should have a _workspace directory_ mounted,
where data and configuration files are stored.

. The container can be used as command-line tool, using a helper script.
+
In this case, you will build your own container image,
and use it within a directory on your local machine via a helper script.

. It can also be used in a cloud environment, with an appropriate sidecar or wrapper.
+
In this case, you will need to add an appropriate API and file and process handling yourself.

This documentation mainly describes the first scenario.

=== Running as "build tool"

The tools are split into steps of a "compilation pipeline".

We use Ant as orchestration tool.
Other orchestration systems would be possible too.

The steps in the pipeline are typically small scripts and XSLT transformations.

== Running on a local machine

For now, you need to follow the steps for xref:development:index.adoc#_setting_up_a_development_environment[Setting up a development environment],
to create a local Docker container image.

You can then run the engine in a container on your local machine,
using the helper script.

By default, the current directory will be mounted as _workspace_.

.List the available options in the engine
  $ aida-s2i -p

.Create a skeleton structure of workspace directories
  $ aida-s2i init

== Next steps

* Look at handling multiple workspaces via the xref:workspace.adoc[].
* The build process creates xref:ant-results.adoc[] that can be read as XML or JSON data.
