= IATI Workbench

_Scripts and tools to investigate IATI data, provide feedback on data quality, etc._

The https://iatistandard.org[IATI Standard^] offers an XML-based standard format to exchange information on activities in international development cooperation and humanitarian aid.

IATI data is published by a variety of actors in this field.
The official list of publishers and available IATI data sets is held in the https://iatiregistry.org[IATI Registry^].

Working with IATI files poses a couple of challenges:

* Multiple versions of the IATI Standard.
* Various levels of coverage of the many possible elements.
* Plenty of errors and inconsistencies in the data.

There are several tools and platforms that ingest IATI data and make it available in formats other than XML.
There are few tools that will help in processing IATI data in its original XML format.

This repository intends to collect scripts and applications to work with IATI files.

== IATI workbench

All tools for the IATI Workbench are packaged in a container that you can run as a command.

=== Using a local workspace directory

The iati-workbench uses the directory `/workspace` as working area for files.

It is possible to "bind mount" a local directory to this location, and have access to the files.

[IMPORTANT]
====
In the current version, a lot of output files are still only available in the workspace folder,
so mounting a local directory to the /workspace folder is basically required.
====

For the "bind mount" to work well in practice, the user and group id in the host system and the container should be the same. 

By default, the container runs as user and group with id 1000.
If this matches the user and group id of the host system, it is possible to simply mount a local folder.

For user ids other than 1000, it is advised to build a local Docker container image tailored to the current user.

  $ docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t iati-workbench:local .

By also using the Docker image tag `local`, it is possible to run the specific version on the local machine.

  $ iati-workbench -t local ...
