= Workspaces

== Workspace location

When running within a Docker container, the scripts use the directory

  /workspace/

as the starting point for all subdirectories with data.

[NOTE]
====
When running via the helper script,
the current directory is mounted into this location.
====

To use a subdirectory in the workspace,
the environment property `workspace` should be set.

When running within the container:

  $ ant -Dworkspace=clientA <target>

When using the container image with the calling script:

  $ aida-s2i -xml -w clientA <target>

The workspace name can contain multiple levels.

=== Running on a local machine

Consider you have a local machine set up with a directory structure:

[source, treeview]
----
~/workspaces
├── clientA
│   ├── config
│   ├── dest
│   ├── input
│   ├── output
│   ├── reports
│   ├── src
│   ├── tmp
│   ├── build.xml
│   ├── .gitignore
│   └── README.adoc
├── clientB
│   └── ...workspace dirs...
└── ...other clients...
----

==== Option 1: go into each client directory and run aida-s2i there

  $ cd ~/workspaces/clientA
  $ aida-s2i ...

==== Option 2: run aida-s2i with -w from the main workspaces directory

  $ cd ~/workspaces
  $ aida-s2i -w s2i/clientA ...

== Workspace structure

The directories within the workspace have grown organically,
mostly starting out as intermediate "pipes" between steps.

config:: Configuration files for the workspace.
dest:: (not used; for validation pipelines)
input:: User-supplied input files
output:: Deliverable files (for s2i in limited use)
reports:: Output to be presented to the user (for s2i not used?)
src:: IATI source files (output of S2I, input for validation etc)
tmp:: Temporary files, using filename extensions as "sub stages".
Cleared with `aida-s2i clean` to reprocess input files.
