= Version releases

We use https://github.com/conventional-changelog/standard-version[Standard Version^]
to update version numbers and the CHANGELOG.
This relies on using the https://www.conventionalcommits.org/en/v1.0.0/[Conventional Commits^]
approach to describing git commit message headers.

== Setup

The file `package.json` contains the configuration under the key "standard-version".

The npm scripts to do releases are only available on the `main` branch.

== Add a new version

When creating a next version, Standard Version will:

- determine the next version number (using semantic versioning);
- update the version number in several files;
- add a section to the `CHANGELOG.md` file;
- commit these changes;
- and add the version number as tag in git.

.Create a new version
  $ npm run release:main

.Create a preview version
  $ npm run release:preview

[NOTE]
====
Each preview release will create its own section in the changelog.

For the full release, we may combine all entries into a single section for that version.

This requires some additional work, amending the release commit
and moving the version tag.
====
