= Spreadsheets2IATI

Convertor.

== Setup notes

=== Workspace

Create a directory for the workspace if it does not exist.

Initialise the workspace, for instance with `iati-workbench init`

Create or copy a `build.xml` to have local build capabilities: for instance to get files from a folder synchronised with Google Drive.

== Spreadsheets2IATI

The conversion process runs within a container.

.Sequence for `s2i-run` target
[plantuml]
....
@startuml
start
$important_color:config/iati-workbench.properties]

$node_1_main_color:inputs/*.*]
:postprocess inputs;
note $important_color
  TODO: check if needed
  Rename files, remove
  empty files, etc. 
  override via local ""build.xml""
end note
$node_1_main_color:updates inputs/*]

partition spreadsheet-map {
  partition sheets-csvxml {
    fork
      $node_1_main_color:input/*.xsl{x} ]
      :excel-csv;
      $node_1_main_color:tmp/*.csv]
    fork again
      $node_1_main_color:input/*.csv]
      :csv-csv;
      $node_1_main_color:tmp/*.csv]
    end fork
    
    :csv-csvxml;
    note: using basex
    $node_1_main_color:tmp/*.csv.xml]
  }
  
  :create map;
  $node_1_main_color:output/csvmap-csv]
  
}

:generate-iati-partials;
note: extension point
fork
  partition sheets-iati {
    :sheets-csvxml;
    note
      already done in step
      ""spreadsheet-map"" above
    end note
    $node_1_main_color:tmp/*.csv.xml]
    
    $important_color:config/csvxml-iati.xslt]
    note
      Can include or override
      default templates
    end note
    :sheets-iati;
  }
fork again
  partition iatixml-iati {
    $node_1_main_color:input/*.iati.xml]
    :iatixml-iati;
  }
fork again
  partition akvo {
    $important_color::Optional Akvo target in
    config/build.iati-workbench.xml;
    $node_1_main_color:input/*.akvo.xml]
    $important_color:config/akvo-s2i.xslt]
    :akvo-s2i;
  }
end fork

$node_1_main_color:tmp/*.generated.xml]

:merge-iati;
$node_1_main_color:src/iati-{activities, organisation}.xml]

:postprocess iati;
note $important_color
  TODO: check if needed
  Fix known data errors, 
  anonymisation, etc
  override via local ""build.xml""
end note

stop
@enduml
....
