= Spreadsheets2IATI

Convertor.

== Setup notes

=== Workspace

Create a directory for the workspace if it does not exist.

Initialise the workspace, for instance with `iati-workbench init`

Create or copy a `build.xml` to have local build capabilities: for instance to get files from a folder synchronised with Google Drive.

== Spreadsheets2IATI

The conversion process initiated by local `ant` in workspace.

The local `build.xml` includes a workspace library build via a hardcoded link.

.Sequence for `s2i-run` target: workspace
[plantuml]
....
@startuml
start
$important_color:config/iati-workbench.properties]
:get inputs;
note
  Uses rclone and local auth
  //Flat// (default) or //deep// (recursive)
end note

$node_1_main_color:inputs/*.*]
:postprocess inputs;
note
  Rename files, remove
  empty files, etc. 
  override via local ""build.xml""
end note
$node_1_main_color:updates inputs/*]

#orange:prepare new inputs;
(1)
....

.IATI Workbench container
[plantuml]
....
@startuml
(1)
partition spreadsheet-map {
  partition sheets-csvxml {
    fork
      $node_1_main_color:input/*.xsl{x} ]
      :excel-csv;
      $node_1_main_color:tmp/*.csv]
    fork again
      $node_1_main_color:input/*.csv]
      :csv-csv;
      $node_1_main_color:tmp/*.csv]
    end fork
    
    :csv-csvxml;
    note: using basex
    $node_1_main_color:tmp/*.csv.xml]
  }
  
  :create map;
  $node_1_main_color:output/csvmap-csv]
  
}
(2)
....

.Workspace
[plantuml]
....
@startuml
(2)
:prepare new inputs:
store changes;
note
  Commit changes to git
  Open diff in browser
end note

#orange:spreadsheets-iati;
(3)
....

.IATI Workbench container
[plantuml]
....
@startuml
(3)
$group_main_color:gather-input-files;
fork
  partition sheets-csvxml {
    fork
      $node_1_main_color:input/*.xsl{x} ]
      :excel-csv;
      $node_1_main_color:tmp/*.csv]
    fork again
      $node_1_main_color:input/*.csv]
      :csv-csv;
      $node_1_main_color:tmp/*.csv]
    end fork
    
    :csv-csvxml;
    note: using basex
    $node_1_main_color:tmp/*.csv.xml]
  }
fork again
  partition collect-iati-files {
    $node_1_main_color:input/**/*.{iati|akvo}.xml ]
    :copy;
    $node_1_main_color:tmp/*.{iati|akvo}.xml ]
  }
end fork
(4)
....

.IATI Workbench container
[plantuml]
....
@startuml
(4)
$group_main_color:generate-iati-partials;
note: extension point
fork
  partition csvxml-s2i {
    $node_1_main_color:tmp/*.csv.xml]
    
    $important_color:config/csvxml-iati.xslt]
    note
      Can include or override
      default templates
    end note
    :csvxml-s2i;
  }
fork again
  partition iati-s2i {
    $node_1_main_color:tmp/*.iati.xml]
    :iati-s2i;
  }
fork again
  partition akvo-s2i {
    $node_1_main_color:tmp/*.akvo.xml]
    $important_color:config/akvo-s2i.xslt]
    note
      Expects an Akvo-specific
      config file.
    end note
    :akvo-s2i;
  }
end fork

$node_1_main_color:tmp/*.generated.xml]
(5)
....

.IATI Workbench container
[plantuml]
....
@startuml
(5)
$group_main_color:create-iati-output;

:merge-iati;
$node_1_main_color:src/iati-{activities, organisation}.xml]
:validate-iati;

$node_1_main_color:via dest/*
reports/*]

:filter-activities;

$node_1_main_color:src/iati-{activities,organisation}.xml
output/iati-activities{,.invalid}.xml
reports/*]
(6)
....

.Workspace
[plantuml]
....
@startuml
(6)
:postprocess iati;
note
  Fix known data errors, 
  anonymisation, etc
  override via local ""build.xml""
end note

:open reports;
note
  Open all feedback files
  in a browser
end note

stop
@enduml
....

.The dependencies of Ant targets involved in `spreadsheet-iati`
image::image$ant-spreadsheet-iati.svg[] 

== IATI Summary

Creates spreadsheets with summary information based on XML fils in the `output` folder.

To create those XML files in the output folder, we need to run a validation and then filter activities.
 