= Spreadsheets2IATI

Combine and convert spreadsheets and IATI files into a single set of files
for IATI activities and IATI organisations.

== Setup notes

=== Workspace

Create a directory for the workspace if it does not exist.

Initialise the workspace, for instance with `aida-s2i init`

== Spreadsheets2IATI

The conversion process is initiated by a local call of `aida-s2i` in the workspace.

  $ aida-s2i spreadsheet-iati

The process breaks down in a couple of components.

.Sequence for `spreadsheet-iati`
[plantuml]
----
start

partition spreadsheet-iati {
$group_main_color:gather-input-files;
note right: Prepare input files from input/ to tmp/

$group_main_color:generate-iati-partials;
note right: Generate IATI for each file individually

$group_main_color:create-iati-output;
note right
  Merge generated IATI into one file and
  (not in AIDA) filter out into valid and invalid activities
end note
}

stop
----

=== Gather input files

This step takes files from the input folder,
and prepares them for processing, in a flat `tmp` folder.

* Excel files are converted into CSV.
* Excel and CSV are then converted into an XML format.
* Akvo and IATI XML files are copied.

[plantuml]
----
start

$group_main_color:gather-input-files;
fork
  partition sheets-csvxml {
    fork
      $node_1_main_color:input/*.xsl{x} ]
      :excel-csv;
      $node_1_main_color:tmp/*.csv]
    fork again
      $node_1_main_color:input/*.csv]
      :csv-csv;
      $node_1_main_color:tmp/*.csv]
    end fork

    :csv-csvxml;
    note: using basex
    $node_1_main_color:tmp/*.csv.xml]
  }
fork again
  partition collect-iati-files {
    $node_1_main_color:input/**/*.{iati|akvo}.xml ]
    :copy;
    $node_1_main_color:tmp/*.{iati|akvo}.xml ]
  }
end fork
(1)
----

=== Generate IATI partials

This step transforms prepared input files into "partial IATI" files.
These intermediary files are not valid IATI yet,
but contain the IATI representation for the particular input file.

[plantuml]
----
(1)
$group_main_color:generate-iati-partials;
note: extension point
fork
  partition csvxml-s2i {
    $node_1_main_color:tmp/*.csv.xml]

    $important_color:config/csvxml-iati.xslt]
    note
      Can include or override
      default templates
    end note
    :csvxml-s2i;
  }
fork again
  partition iati-s2i {
    $node_1_main_color:tmp/*.iati.xml,*.akvo.xml]
    :iati-s2i;
  }
end fork

$node_1_main_color:tmp/*.generated.xml]
(2)
----

=== Create IATI output

This step combines all "partial IATI files" into one IATI activities and one IATI organisations file.
These files can contain activities that are not IATI schema-compliant.

[plantuml]
----
(2)
$group_main_color:create-iati-output;

:merge-iati;
$node_1_main_color:src/iati-{activities, organisation}.xml]

stop
----

== Ant targets in the IATI Workbench

.The dependencies of Ant targets involved in `spreadsheet-iati`
image::image$ant-spreadsheet-iati.svg[]
