= Spreadsheets2IATI

Convertor.

== Setup notes

=== Workspace

Create a directory for the workspace if it does not exist.

Initialise the workspace, for instance with `iati-workbench init`

Create or copy a `build.xml` to have local build capabilities: for instance to get files from a folder synchronised with Google Drive.

== Spreadsheets2IATI

The conversion process initiated by local `ant` in workspace.

The local `build.xml` includes a workspace library build via a hardcoded link.

.Sequence for `s2i-run` target
[plantuml]
....
@startuml
|Workspace|
start
$important_color:config/iati-workbench.properties]
:get inputs;
note
  Uses rclone and local auth
  //Flat// (default) or //deep// (recursive)
end note

$node_1_main_color:inputs/*.*]
:postprocess inputs;
note
  Rename files, remove
  empty files, etc. 
  override via local ""build.xml""
end note
$node_1_main_color:updates inputs/*]

|Workspace|
#orange:prepare new inputs;

|IATI Workbench|
partition spreadsheet-map {
  partition sheets-csvxml {
    fork
      $node_1_main_color:input/*.xsl{x} ]
      :excel-csv;
      $node_1_main_color:tmp/*.csv]
    fork again
      $node_1_main_color:input/*.csv]
      :csv-csv;
      $node_1_main_color:tmp/*.csv]
    end fork
    
    :csv-csvxml;
    note: using basex
    $node_1_main_color:tmp/*.csv.xml]
  }
  
  :create map;
  $node_1_main_color:output/csvmap-csv]
  
}

|Workspace|
:prepare new inputs:
store changes;
note
  Commit changes to git
  Open diff in browser
end note

#orange:spreadsheets-iati;

|IATI Workbench|
:generate-iati-partials;
note: extension point
fork
  partition sheets-iati {
    :sheets-csvxml;
    note
      already done in step
      ""spreadsheet-map"" above
    end note
    $node_1_main_color:tmp/*.csv.xml]
    
    $important_color:config/csvxml-iati.xslt]
    note
      Can include or override
      default templates
    end note
    :sheets-iati;
  }
fork again
  partition iatixml-iati {
    $node_1_main_color:input/*.iati.xml]
    :iatixml-iati;
  }
fork again
  partition akvo {
    $important_color::Optional Akvo target in
    config/build.iati-workbench.xml;
    $node_1_main_color:input/*.akvo.xml]
    $important_color:config/akvo-s2i.xslt]
    :akvo-s2i;
  }
end fork

$node_1_main_color:tmp/*.generated.xml]

:merge-iati;
$node_1_main_color:src/iati-{activities, organisation}.xml]
:validate-iati;

$node_1_main_color:via dest/*
reports/*]

:filter-activities;

$node_1_main_color:src/iati-{activities,organisation}.xml
output/iati-activities{,.invalid}.xml
reports/*]

|Workspace|
:postprocess iati;
note
  Fix known data errors, 
  anonymisation, etc
  override via local ""build.xml""
end note

|Workspace|
:open reports;
note
  Open all feedback files
  in a browser
end note

|Workspace|
stop
@enduml
....

== IATI Summary

Creates spreadsheets with summary information based on XML fils in the `output` folder.

To create those XML files in the output folder, we need to run a validation and then filter activities.
 