name: Generate docs website
on:
  push:
    branches:
      - main
      - develop
      - feature/iati-tools

jobs:
  antora:
    runs-on: ubuntu-latest
    container: node:16-buster

    services:
      kroki:
        image: yuzutech/kroki

    steps:
      - name: Get the sources
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup Antora
        run: npm ci

      - name: Generate docs site
        run: npm run docs

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/site
          publish_branch: gh-pages
